server:
  port: 8081

management:
  endpoints:
    enabled-by-default: true
    web.base-path: /
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8071